# Verwenden des Ausgangsbildes
FROM bjoernbahndlr/ostar:oval

WORKDIR /home/carla

# Kopieren des Skripts in den Container
COPY ./startScriptSingleContainer2.sh ./startScriptSingleContainer2.sh

CMD ["sh", "./startScriptSingleContainer2.sh"]

